/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    "text-white",
    "text-black",
    "bg-white",
    "bg-black",
    "border-white",
    "border-black",
    "hover:text-black",
    "hover:text-white",
    "hover:bg-white",
    "hover:bg-black",
    "hover:border-white",
    "hover:border-black",
    "opacity-0",
    "opacity-100",
    "hover:bg-[#1F1F1F]",
    "hover:bg-[#1338F3]",
    "hover:bg-[#14C5FD]",
    "hover:bg-[#FE6F1D]",
    "hover:bg-[#E4AF12]",
    "hover:bg-[#28E98C]",
    "bg-[#1F1F1F]",
    "bg-[#1338F3]",
    "bg-[#14C5FD]",
    "bg-[#FE6F1D]",
    "bg-[#E4AF12]",
    "bg-[#28E98C]",
    "hover:border-black",
    "hover:border-white",
    "hover:border-[#1338F3]",
    "hover:border-[#14C5FD]",
    "hover:border-[#FE6F1D]",
    "hover:border-[#E4AF12]",
    "hover:border-[#28E98C]",
    "border-black",
    "border-white",
    "border-[#1338F3]",
    "border-[#14C5FD]",
    "border-[#FE6F1D]",
    "border-[#E4AF12]",
    "border-[#28E98C]",
    "hover:text-[#1338F3]",
    "hover:text-[#14C5FD]",
    "hover:text-[#FE6F1D]",
    "hover:text-[#E4AF12]",
    "hover:text-[#28E98C]",
    "text-[#1338F3]",
    "text-[#14C5FD]",
    "text-[#FE6F1D]",
    "text-[#E4AF12]",
    "text-[#28E98C]",
  ],
};
